### ISSUE TITLE
Add Reporting module as supporting module in the Readme 

### ISSUE THREAD

**Issue by abbedsedk** [vmware-samples/power-validated-solutions-for-cloud-foundation#202]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

2.0.0.1010

### Motivation

Hi i just saw your [blog post](https://blogs.vmware.com/cloud-foundation/2023/01/31/vmware-validated-solutions-jan-2023-update/) from vmware-validated-solutions-jan-2023-update,
and wanted to test-out:

- Added full automation capabilities to PowerValidatedSolutions, including:

    Invoke-PasswordPolicyManager – a dedicated cmdlet to generate an HTML report showing the existing configuration across the platform without configuration drift

I've gone through the installation [link](https://www.powershellgallery.com/packages/PowerValidatedSolutions/2.0.0.1010)
`Install-Module -Name PowerValidatedSolutions` 
Then from there the link here [Project Site] to install the supporting module
`Set-PSRepository -Name PSGallery -InstallationPolicy Trusted`
`Install-Module -Name VMware.PowerCLI -MinimumVersion 12.7.0`
`Install-Module -Name VMware.vSphere.SsoAdmin -MinimumVersion 1.3.8`
`Install-Module -Name ImportExcel -MinimumVersion 7.1.1`
`Install-Module -Name PowerVCF -MinimumVersion 2.2.0`
`Install-Module -Name PowerValidatedSolutions -MinimumVersion 2.0.0`
i got the syntaxe from the -Examples and choose the Example 1
`Get-Help -Name Invoke-PasswordPolicyManager -Examples`

At that point i got a bunch of time a function missing
`Convert-CssClass`
After a quick search i found this function is in Reporting module,
thus my suggestion to add it in the Readme.

### Suggestion

https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation#installing-the-module
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module -Name VMware.PowerCLI -MinimumVersion 12.7.0
Install-Module -Name VMware.vSphere.SsoAdmin -MinimumVersion 1.3.8
Install-Module -Name ImportExcel -MinimumVersion 7.1.1
Install-Module -Name PowerVCF -MinimumVersion 2.2.0
Install-Module -Name PowerValidatedSolutions -MinimumVersion 2.0.0
Install-Module -Name VMware.CloudFoundation.Reporting -MinimumVersion 1.0.6.1004

**Comment by GaryJBlake** [comment]
Thanks @abbedsedk I can confirm that this is a bug, we actually don't need the `Convert-CssClass` function for the Password Policy Manager functions. This is a miss when we transferred over some functions from the reporting module.
