### ISSUE TITLE
Add-vCenterGlobalPermission gives "Get-GlobalPermission : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again."

### ISSUE THREAD

**Issue by cybernils** [vmware-samples/power-validated-solutions-for-cloud-foundation#209]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.0

### Module Version

2.0.0.1010

### PowerShell Version

5.1.19041.2364

### PowerCLI Version

12.7.0

### PowerVCF Version

2.2.0

### Guest Operating System

Windows 10

### Description

The Add-vCenterGlobalPermission cmdlet and keep getting the following error: "Get-GlobalPermission : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again." 

### Error or Debug Output

"Get-GlobalPermission : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again." 

### Expected Behavior

No errors.

### Actual Behavior

the Add-vCenterGlobalPermission cmdlet and keep getting the following error: "Get-GlobalPermission : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again." 

### Steps to Reproduce

The Add-vCenterGlobalPermission cmdlet and keep getting the following error: "Get-GlobalPermission : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again." 

Changing from UseBasicParsing = $false to UseBasicParsing = $true in PowerValidatedSolutions.psm1 solved the issue.

**Comment by GaryJBlake** [comment]
**Investigation**

Investigated the issue and this is caused due to incorrect setting for UesBasicParsing within the `Get-GlobalPermission` function.

Line: 23146 is UseBasicParsing = $false and should be UseBasicParsing = $true

**Workaround**

To workaround this issue until the fix is published you have two options:

1. Launch Microsoft Edge at least once
2. Manually amend line 23146 by changing $false to $true
