### ISSUE TITLE
Test-VCFAuthentication function improvement

### ISSUE THREAD

**Issue by devivmware** [vmware-samples/power-validated-solutions-for-cloud-foundation#216]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Validate SDDC root password also in Test-VCFAuthentication function.

### Use Case(s)

Validate SDDC root password also in Test-VCFAuthentication function. If we validate root password also in the beginning, we might not see failures in mid of the script. (especially when using VCF reporting module).

### Potential Configuration

Validate SDDC root password also in Test-VCFAuthentication function. If we validate root password also in the beginning, we might not see failures in mid of the script. (especially when using VCF reporting module).

**Comment by GaryJBlake** [comment]
Validating the root account would be considered out of scope for the purpose of `Test-VCFAuthentication`, its use case is the ability to check REST API authentication only.

Checking the root account is not possible with a direct connection as SSH for root is disabled by default, the only options here are to validate in one of the following ways:

- Via a Console window
- SSH as vcf user and su to root
- PowerCLI and `Invoke-VMScript` cmdlet to connect via vCenter Server and VM Tools to verify you can login

I'm assuming this feature improvement is based on your recent usage of `VMware.CloudFoundation.Reporting` which uses various functions from `PowerValidatedSolutions` where currently you need to supply the SDDC Manager root password. There are plans to enhance `VMware.CloudFoundation.Reporting` where the root access requirement is derived to pivot over to use the Public REST APIs for starting the health check operation and then retrieving the zip file, this would then eliminate the need for root access in favour of REST API.

I'm going to decline this feature request on the basis that we plan to implement the following https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/issues/96 enhancement to `VMware.CloudFoundation.Reporting`.
