### ISSUE TITLE
`Add-vRLIAuthenticationGroup` fails with "The remote server returned an error: (404) Not Found"

### ISSUE THREAD

**Issue by cybernils** [vmware-samples/power-validated-solutions-for-cloud-foundation#223]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.0

### Module Version

2.0.0.1010

### PowerShell Version

5.1.19041.2364

### PowerCLI Version

12.7.0

### PowerVCF Version

2.2.0

### Guest Operating System

Windows 10

### Description

`Add-vRLIAuthenticationGroup` fails with "The remote server returned an error: (404) Not Found". 

Copying from the variables into the GUI doing the manual procedure for "Assign vRealize Log Insight Roles to Active Directory Groups" works.

### Error or Debug Output

```powershell
Get-vRLIGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:8220 char:39
+ ...                        if (!(Get-vRLIGroup -authProvider vidm | Where ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vRLIGroup
Add-vRLIGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:8221 char:37
+ ...             Add-vRLIGroup -authProvider vidm -domain $domain -group $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-vRLIGroup
Get-vRLIGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.0.0.1010\PowerValidatedSolutions.psm1:8222 char:41
+ ...                          if (Get-vRLIGroup -authProvider vidm | Where ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vRLIGroup
```

### Expected Behavior

The groups to be added in vRLI.

### Actual Behavior

"The remote server returned an error: (404) Not Found"

### Steps to Reproduce

```powshell
Add-vRLIAuthenticationGroup -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $domain -group $vrliAdminGroup -role 'Super Admin'
Add-vRLIAuthenticationGroup -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $domain -group $vrliUserGroup -role 'User'
Add-vRLIAuthenticationGroup -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $domain -group $vrliViewerGroup -role 'View Only Admin'
```

**Comment by tenthirtyam** [comment]
I've applied code formatting to the issue description for readability.

**Comment by lksece** [comment]
Observed the same issue on VCF 451 env with PVS 2.3.0.1005.

Add-vRLIAuthenticationGroup -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManage
rPass -domain $domain -group $vrliAdminGroup -role 'Super Admin'
Get-vRLIGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.3.0.1005\PowerValidatedSolutions.psm1:8179
char:39
+ ...                        if (!(Get-vRLIGroup -authProvider vidm | Where ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vRLIGroup

Add-vRLIGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.3.0.1005\PowerValidatedSolutions.psm1:8180
char:37
+ ...             Add-vRLIGroup -authProvider vidm -domain $domain -group $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-vRLIGroup

Get-vRLIGroup : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.3.0.1005\PowerValidatedSolutions.psm1:8181
char:41
+ ...                          if (Get-vRLIGroup -authProvider vidm | Where ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vRLIGroup

WARNING: Adding Group to vRealize Log Insight (sfo-vrli01.sfo.rainpole.io), named (gg-vrli-admins):
POST_VALIDATION_FAILED

**Comment by GaryJBlake** [comment]
On further investigation the original API /api/v1/authgroups/$authProvider is no longer available for version newer than vRealize Log Insight 8.6.2. I've been unable to establish a replacement API either. 

I'm going to add a version check into the `Add-vRLIAuthenticationGroup` cmdlet to throw a Warning if the version is later than 8.6.2 that instructs the user to following the UI procedures.

**Comment by GaryJBlake** [comment]
Version check not working consistently
