### ISSUE TITLE
Get-vCenterServerDetail missing example

### ISSUE THREAD

**Issue by plearn2023** [vmware-samples/power-validated-solutions-for-cloud-foundation#234]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Based on the cmdlet `Get-vCenterServerDetail` it is difficult to understand how to execute this command.
An example would really help.
Also, i seen we are referred `-server` well it is not server it is sddcmanager, so i would suggest to change this to `sddcmanager` and everywhere we are using ´-password´, it would be good idea to change `-pass` to `-password`

### Use Case(s)

Better understanding of the command.

### Potential Configuration

Standard Powershell guideliness to update example

**Comment by tenthirtyam** [comment]
> Also, i seen we are referred -server well it is not server it is sddcmanager, so i would suggest to change this to sddcmanager and everywhere we are using ´-password´, it would be good idea to change -pass to -password

An example would be sufficient in my opinion, otherwise it’s a breaking change in any sources that are dependent. 

i’d suggest rather than a single issue for an example, a technical debt issue for providing more complete examples across exported functions.
