### ISSUE TITLE
Add-vRSLCMNtpServer fails with PRE_VALIDATION_FAILED error message for valid time server

### ISSUE THREAD

**Issue by lksece** [vmware-samples/power-validated-solutions-for-cloud-foundation#263]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.4.1

### Module Version

2.3.0.1005

### PowerShell Version

5.1.14393.5582

### PowerCLI Version

13.0.0 -revision 20829139

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2016

### Description

Doc :
https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-site-protection-and-disaster-recovery-v1/GUID-5E4C6DE8-0D09-4904-AD09-D533F461328F.html

Define the variable and run the below command:

$sddcManagerFqdn = "sfo-vcf01.sfo.rainpole.io"
$sddcManagerUser = "administrator@vsphere.local"
$sddcManagerPass = "VMw@re123!"
$ntpServer = "ntp.lax.rainpole.io"
$ntpServerDesc = "VCF NTP Server 2"
```powershell
PS F:\platformtools-dev> Add-vRSLCMNtpServer -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -ntpServer $ntpServer -ntpServerDesc $ntpServerDesc
Add-vRSLCMNtpServer : Unable to confirm NTP server ntp.lax.rainpole.io is valid: PRE_VALIDATION_FAILED
At line:1 char:1
+ Add-vRSLCMNtpServer -server $sddcManagerFqdn -user $sddcManagerUser - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-vRSLCMNtpServer
```
### Error or Debug Output

Error : Unable to confirm NTP server ntp.lax.rainpole.io is valid: PRE_VALIDATION_FAILED

Internally it uses Test-NtpServer, but it returns False 
```powershell
PS F:\platformtools-dev> Test-NtpServer -server "ntp.lax.rainpole.io"
False

```
 it returns False for other time server as well.
```powershell
PS F:\platformtools-dev> Test-NtpServer -server pool.ntp.org
False 
```
 

### Expected Behavior

Should be able to configure NTP

### Actual Behavior

PRE_VALIDATION_FAILED

### Steps to Reproduce

Deploy VCF 441
Deploy vRS and DR Solutions
Run the command as specified in the doc.

**Comment by GaryJBlake** [comment]
I’ve been looking into this issue and I’m not able to reproduce, I connected to one of the pipeline test beds to do a quick test and also not able to reproduce. I don’t know if the NTP server was just not responding randomly but it worked against the following NTP server:

- ntp0.sfo.rainpole.io
- ntp.sfo.rainpole.io
- ntp.lax.rainpole.io
- ntp0.lax.rainpole.io

As I can't reproduce on three different setups I'm going to mark this as  an environmental issue.

That said whilst looking at the code I did noticed a couple of small improvements that could be made, for example we don’t check against the description, so an error could be thrown if we try to add a new entry with the same name. Will make these improvements and then make a pull request.
