### ISSUE TITLE
ILA: Error observed while Configuring SMTP for vRealize Log Insight.

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware-samples/power-validated-solutions-for-cloud-foundation#279]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.1 , 5,0

### Module Version

2.3.0.1007

### PowerShell Version

5.1.14393.5582

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2016

### Environment Details

Build :
VCF 451
VCF 5.0

### Description

Observing the below error for all the option from option 10 ILA : Configuring SMTP for vRealize Log Insight.

ERROR The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."

### Error or Debug Output

ERROR The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."

### Expected Behavior

The option should work without any issues

### Actual Behavior

ERROR The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."

### Steps to Reproduce

vRLI - 8.10.2 (Build 21638564)

**Comment by GaryJBlake** [comment]
Following investigation the API for vRLI has been updated in later versions, initial discovery has found the following:

- Switch to Bearer Token
- Port 9543 required for PUT, POST or PATCH updates
- v1 and v2 APIs support
