### ISSUE TITLE
 Add-vSphereRole fails with error Cannot validate argument on parameter 'AddPrivilege'

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware-samples/power-validated-solutions-for-cloud-foundation#299]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.0

### Module Version

2.5.0.1008

### PowerShell Version

5.1.14393.5582

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2016

### Description

```powershell
Add-vSphereRole -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -sddcDomain $sddcDomainName -roleName $vroVsphereRoleName
```

### Error or Debug Output

``` powershell
PS C:\Users\Administrator> Add-vSphereRole -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -sddcDomain $sddcDomainName -roleName $vroVsphereRoleName

Get-VIPrivilege : 7/19/2023 7:39:12 AM  Get-VIPrivilege         VIPrivilege with id 'DVPortgroup.Ipfix' was not found using the specified filter(s).
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.5.0.1008\PowerValidatedSolutions.psm1:13717 char:119
+ ... -Role $roleName -AddPrivilege (Get-VIPrivilege -ID $privilege) -Confi ...
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VIPrivilege], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.PermissionManagement.GetVIPrivilege

 Error at Script Line 13717
 Relevant Command: Set-VIRole -Server $vcfVcenterDetails.fqdn -Role $roleName -AddPrivilege (Get-VIPrivilege -ID $privilege) -Confirm:$False -ErrorAction SilentlyContinue | Out-Null
 Error Message: Cannot validate argument on parameter 'AddPrivilege'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PS C:\Users\Administrator> Add-vSphereRole -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -sddcDomain $sddcDomainName -roleName $vroVsphereRoleName
```

### Expected Behavior

Add-vsphereRole should work without any errors

### Actual Behavior

Add-vsphereRole is failing with error

### Steps to Reproduce

Deploy VCF 5.0
Configure PCA
Run the below command or run option 13 in platform tools PCA Management tasks

Add-vSphereRole -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -sddcDomain $sddcDomainName -roleName $vroVsphereRoleName

**Comment by GaryJBlake** [comment]
Key failure here is as follows: VIPrivilege with id 'DVPortgroup.Ipfix' was not found using the specified filter(s).

This role is created based on a clone of the Administrator role and it appears there are a number of changes between vSphre 7 and vSphere 8. For this one its no longer present in vSphere8
