### ISSUE TITLE
Enhance the module to use status codes for API requests

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/power-validated-solutions-for-cloud-foundation#75]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Enhance the module to use API status code, where applicable, for low-level API requests.

### Use Case(s)

Enhanced error handling for API requests.

### Potential Configuration

```powershell
    $results = Invoke-Webrequest -uri https://api.rainpole.io/api/v1/hello -Method Get -headers $headers
    if($results.StatusCode -ne 200) {
        Write-Output "Whoopies!"
        break
    }
```

**Comment by antonystefanov** [comment]
I'll be working on portion of this issue.

**Comment by tenthirtyam** [comment]
This may not be possible in the module. Our code used `Invoke-RestMethod` versus `Invoke-Webrequest`. Based on my research, only the latter with return the status codes, unless there is another option to do so with `Invoke-RestMethod`.

Ryan

**Comment by antonystefanov** [comment]
`Invoke-RestMethod` directly returns JSON and XML to objects while with `Invoke-WebRequest` you have to convert it from JSON to PS objects

Example getting NSXT transport zones:

- Option 1 (`Invoke-RestMethod`)

```
$restMethod = Invoke-RestMethod -Method Get -Uri "https://$nsxtmanager/api/v1/transport-zones" -ContentType application/json -Headers $nsxtHeaders
$results = $restMethod.results
```

- Option 2 (`Invoke-WebRequest`)

```
$webRequest = Invoke-WebRequest -Method Get -Uri "https://$nsxtmanager/api/v1/transport-zones" -ContentType application/json -Headers $nsxtHeaders
$results = ($webRequest.Content | ConvertFrom-Json).results
```


The difference is that with `Invoke-WebRequest` we got some additional properties like Headers, StatusCode and StatusDescription that can be used for error handling

- Invoke-RestMethod

```
PS C:\Windows\system32> $RestMethod | gm


   TypeName: System.Management.Automation.PSCustomObject

Name           MemberType   Definition
----           ----------   ----------
Equals         Method       bool Equals(System.Object obj)
GetHashCode    Method       int GetHashCode()
GetType        Method       type GetType()
ToString       Method       string ToString()
results        NoteProperty Object[] results=System.Object[]
result_count   NoteProperty int result_count=3
sort_ascending NoteProperty bool sort_ascending=True
sort_by        NoteProperty string sort_by=display_name

```
- Invoke-WebRequest

```
PS C:\Windows\system32> $webRequest | gm


   TypeName: Microsoft.PowerShell.Commands.HtmlWebResponseObject

Name              MemberType Definition
----              ---------- ----------
Dispose           Method     void Dispose(), void IDisposable.Dispose()
Equals            Method     bool Equals(System.Object obj)
GetHashCode       Method     int GetHashCode()
GetType           Method     type GetType()
ToString          Method     string ToString()
AllElements       Property   Microsoft.PowerShell.Commands.WebCmdletElementCollection AllElements {get;}
BaseResponse      Property   System.Net.WebResponse BaseResponse {get;set;}
Content           Property   string Content {get;}
Forms             Property   Microsoft.PowerShell.Commands.FormObjectCollection Forms {get;}
Headers           Property   System.Collections.Generic.Dictionary[string,string] Headers {get;}
Images            Property   Microsoft.PowerShell.Commands.WebCmdletElementCollection Images {get;}
InputFields       Property   Microsoft.PowerShell.Commands.WebCmdletElementCollection InputFields {get;}
Links             Property   Microsoft.PowerShell.Commands.WebCmdletElementCollection Links {get;}
ParsedHtml        Property   mshtml.IHTMLDocument2 ParsedHtml {get;}
RawContent        Property   string RawContent {get;set;}
RawContentLength  Property   long RawContentLength {get;}
RawContentStream  Property   System.IO.MemoryStream RawContentStream {get;}
Scripts           Property   Microsoft.PowerShell.Commands.WebCmdletElementCollection Scripts {get;}
StatusCode        Property   int StatusCode {get;}
StatusDescription Property   string StatusDescription {get;}
```

In the Power Validated Solutions mainly `Invoke-RestMethod` is used and a few times `Invoke-WebRequest`

In [PowerShell 7](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.2) `Invoke-RestMethod`  introduce [-StatusCodeVariable <String>] but AFAIK PVS is not yet PS7 compatible

**Comment by tenthirtyam** [comment]
Thanks for the research, Tony. Given that this would be a major overhaul and that our focus is PS5+, we'll table this for future consideration.
